name: WeChat SDK Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        run: |
          npm i
          npm run test
      - name: Upload Test Report
        uses: codecov/codecov-action@v3
        with:
          name: report
          files: coverage/coverage-final.json